language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost1.54-dev

before_script:
  - mkdir Debug
  - cd Debug
  - cmake .. -DCMAKE_BUILD_TYPE=Debug

script:
  - make check
