language: cpp

compiler:
  - gcc
  - clang

before_install:
  - wget -O boost_1_57_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.57.0/boost_1_57_0.tar.gz/download
  - tar xf boost_1_57_0.tar.gz
  - cd boost_1_57_0
  - ./bootstrap.sh
  - sudo ./b2 --with-test install -d0
  - cd ..
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install libc++-dev; fi

before_script:
  - mkdir Debug
  - cd Debug
  - if [ "$CXX" = "g++" ]; then cmake .. -DCMAKE_BUILD_TYPE=Debug; fi
  - if [ "$CXX" = "clang++" ]; then cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=-stdlib=libc++; fi

script:
  - make check
