language: cpp

compiler:
  - gcc

before_install:
  - wget -O boost_1_59_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.tar.gz/download
  - tar xf boost_1_59_0.tar.gz
  - cd boost_1_59_0
  - ./bootstrap.sh
  - sudo ./b2 --with-test --with-program_options install -d0
  - cd ..
  - wget --no-check-certificate http://www.cmake.org/files/v3.1/cmake-3.1.2.tar.gz
  - tar xf cmake-3.1.2.tar.gz
  - cd cmake-3.1.2
  - ./bootstrap
  - sudo make -j4 install
  - cd ..
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-5
  - export CXX="g++-5" CC="gcc-5"

before_script:
  - mkdir Debug
  - cd Debug
  - cmake .. -DCMAKE_BUILD_TYPE=Debug

script:
  - make check
