language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-6
  - export CXX="g++-6" CC="gcc-6"
  - g++-6 --version
  - wget -O boost_1_59_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.tar.gz/download
  - tar xf boost_1_59_0.tar.gz
  - cd boost_1_59_0
  - ./bootstrap.sh
  - sudo ./b2 --with-test --with-program_options install -d0
  - cd ..
  - wget --no-check-certificate https://cmake.org/files/v3.5/cmake-3.5.1.tar.gz
  - tar xf cmake-3.5.1.tar.gz
  - cd cmake-3.5.1
  - ./bootstrap
  - sudo make -j4 install
  - cd ..

before_script:
  - mkdir Debug
  - cd Debug
  - cmake .. -DCMAKE_BUILD_TYPE=Debug

script:
  - make check
